rootProject.name = "BackendFramework"
include("gateway:gateway_rpc")
include("echo_grpc")
include("rpc")
include("echo")
include("player")
include("mongo")
include("test_utils")
include("kubernates")
include("fail")
