apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-load-balancer
spec:
  selector:
    app: gateway
  ports:
    - port: 9000
      nodePort: 30000
      name: tcp
      protocol: TCP
  type: NodePort