apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ludd.echo:0.1
          ports:
            - containerPort: 9001