apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-arbiter
spec:
  selector:
    matchLabels:
      app: mongo-arbiter
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mongo-arbiter
    spec:
      containers:
        - name: mongo-arbiter
          image: mongo-replica-set:4.4
          ports:
            - containerPort: 27017
